mkmall:
  outputs:
    dev:
      account: IPB82815
      database: Analytics
      password: Sachin@10
      role: AnalyticsEngineer
      schema: dbt_sachin
      threads: 3
      type: snowflake
      user: Sachin
      warehouse: transform_wh
  target: dev