ibm_DataCloud:
  target: prod
  outputs:
    prod:
      type: snowflake
      account: "${{ secrets.SNOWFLAKE_ACCOUNT }}"
      user: "${{ secrets.SNOWFLAKE_USER }}
      password: "${{ secrets.SNOWFLAKE_PASSWORD }}"
      role: AnalyticsEngineer
      database: ANALYTICS
      warehouse: TRANSFORM_WH
      schema: PROD
      threads: 4


